### ISSUE TITLE
The order of buttons is random.

### ISSUE THREAD

**Issue by gaborbencebekesi** [PaystackHQ/library-android-pinpad#2]

**Comment by ibrahimlawal** [comment]
There's a setting to make it non-random: `place_digits_randomly`. Set it to false to keep them ordered.

Full list here: https://github.com/PaystackHQ/android-pinpad/blob/396d0b3ad836e3ee948ef675425fa2a83d34d381/pinpad/src/main/res/values/attrs_pinpadview.xml


—
Ibrahim Lawal | Customer Success Engineer


@ibrahimlawal on Payslack | Join us via http://slack.paystack.com
@ibrahimlawal on GitHub
@ibrahimlawal on Twitter
Skype:profibro


Paystack Payments Limited
3A, Ladoke Akintola Street, Ikeja GRA.
Office Phone: +234 908 566 2909




www.paystack.com 

--- original message ---
On Thu, Sep 14, 2017 at 03:26 pm, <notifications@github.com> gaborbencebekesi wrote:


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by gaborbencebekesi** [comment]
Oh, it's not a bug, it's a feature! Nice!
Thank you!
